version: "3"

services:
  pg-server:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ~/Documentos/Chavi/nestjs/pg:/var/lib/postgresql/data
